version:     "3.0--01-Mar-2022"
copyright:   "2022"
author:      "Muhammad Farhan Ramadhan"
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/farhan1117/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
